/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 21-jul.-2019 2:06:10 a. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS BOMBERMAN2 CASCADE
;

/* Create Tables */

CREATE TABLE BOMBERMAN2
(
	Jugador varchar(40) NOT NULL,
	Puntos integer NOT NULL   DEFAULT 0
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE BOMBERMAN2 ADD CONSTRAINT PK_Table1
	PRIMARY KEY (Jugador)
;
